services:
  # Backend service
  - type: web
    name: ft-transcendence-backend
    env: node
    region: oregon
    plan: starter
    buildCommand: cd packages/backend && npm install && npm run build
    startCommand: cd packages/backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_PATH
        value: /var/data/database.sqlite
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: SESSION_SECRET
        generateValue: true
      - key: PORT
        value: 3000
    disk:
      name: sqlite-data
      mountPath: /var/data
      sizeGB: 1

  # Frontend service
  - type: web
    name: ft-transcendence-frontend
    env: static
    region: oregon
    plan: starter
    buildCommand: cd packages/frontend && npm install && npm run build
    staticPublishPath: ./packages/frontend/dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
