services:
  # Backend service
  - type: web
    name: ft-transcendence-backend
    runtime: node
    region: singapore
    plan: free
    rootDir: packages/backend
    buildCommand: corepack enable && corepack prepare pnpm@10.19.0 --activate && cd ../.. && pnpm install --frozen-lockfile && cd packages/backend && pnpm run build
    startCommand: pnpm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_PATH
        value: /var/data/database.sqlite
      - key: BACKEND_URL
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: SESSION_SECRET
        generateValue: true
      - key: PORT
        value: 10000
    disk:
      name: sqlite-data
      mountPath: /var/data
      sizeGB: 1

  # Frontend service
  - type: web
    name: ft-transcendence-frontend
    runtime: static
    region: singapore
    plan: free
    rootDir: packages/frontend
    buildCommand: corepack enable && corepack prepare pnpm@10.19.0 --activate && cd ../.. && pnpm install --frozen-lockfile && cd packages/frontend && pnpm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_URL
        sync: false
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
